# azure-pipelines.yml
trigger:
  branches:
    include:
      - main   # Run pipeline when code is pushed to main

pool:
  vmImage: 'ubuntu-latest'   # Use Linux agent for Angular builds


variables:
  buildConfiguration: 'production'

stages:
  - stage: Build
    displayName: 'Build Angular App'
    jobs:
      - job: BuildAngular
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'   # Install Node.js
            displayName: 'Install Node.js'

          - script: npm install -g @angular/cli
            displayName: 'Install Angular CLI'

          - script: npm install
            displayName: 'Install dependencies'

          - script: npm run build-prod
            displayName: 'Build Angular app (production)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist/tinyweb-app'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployAngular
        steps:
          - task: AzureWebApp@1

            inputs:
              azureSubscription: 'AzureSubscription-Prod'
              appName: 'tinyweb-app'
              appType: 'webApp'
              package: '$(Pipeline.Workspace)/drop'

            