# azure-pipelines.yml

trigger:
  branches:
    include:
      - main   # Run pipeline when code is pushed to main

pool:
  vmImage: 'ubuntu-latest'   # Use Linux agent for Angular builds
  # name: tinyweb-apppool


variables:
  node_version: '20.x'
  buildConfiguration: 'production'
  angularProject: 'tinyweb-app'   # Replace with your Angular project name


stages:
  - stage: Build
    displayName: 'Build Angular App'
    jobs:
      - job: BuildAngular
        steps:
        
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Use Node.js $(node_version)'

          - script: |
              npm install -g @angular/cli
              npm install
            displayName: 'install dependencies'

          - script: 
              npm run build:ssr
            workingDirectory: tinyweb-app
            displayName: 'Build angular app'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'dist/tinyweb-app/browser'
              artifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish build artifacts'
